### ISSUE TITLE
Improve error handling if ML Kit is not working?

### ISSUE THREAD

**Issue by szescxz** [Fabi019/hid-barcode-scanner#170]
I'm experiencing an issue when camera preview is working but the app could not recognize any barcodes. Until I checked the logcat:
```
03-06 19:33:29.098 30992   879 D BarcodeAnalyser: Processing image
03-06 19:33:29.100 30992  6018 W DynamiteModule: Local module descriptor class for com.google.mlkit.dynamite.barcode not found.
03-06 19:33:29.110 30992   879 E BarcodeAnalyser: Error waiting for task
03-06 19:33:29.110 30992   879 E BarcodeAnalyser: r6.a: Waiting for the barcode module to be downloaded. Please wait.
03-06 19:33:29.110 30992   879 E BarcodeAnalyser: 	at a7.l.c(Unknown Source:237)
03-06 19:33:29.110 30992   879 E BarcodeAnalyser: 	at b4.k0.run(Unknown Source:52)
03-06 19:33:29.110 30992   879 E BarcodeAnalyser: 	at l.h.run(Unknown Source:108)
03-06 19:33:29.110 30992   879 E BarcodeAnalyser: 	at f5.g.run(Unknown Source:28)
03-06 19:33:29.110 30992   879 E BarcodeAnalyser: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-06 19:33:29.110 30992   879 E BarcodeAnalyser: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-06 19:33:29.110 30992   879 E BarcodeAnalyser: 	at f5.g.run(Unknown Source:53)
03-06 19:33:29.110 30992   879 E BarcodeAnalyser: 	at java.lang.Thread.run(Thread.java:920)
03-06 19:33:29.111 30992 30992 E BarcodeAnalyser: Error processing image
03-06 19:33:29.111 30992 30992 E BarcodeAnalyser: r6.a: Waiting for the barcode module to be downloaded. Please wait.
03-06 19:33:29.111 30992 30992 E BarcodeAnalyser: 	at a7.l.c(Unknown Source:237)
03-06 19:33:29.111 30992 30992 E BarcodeAnalyser: 	at b4.k0.run(Unknown Source:52)
03-06 19:33:29.111 30992 30992 E BarcodeAnalyser: 	at l.h.run(Unknown Source:108)
03-06 19:33:29.111 30992 30992 E BarcodeAnalyser: 	at f5.g.run(Unknown Source:28)
03-06 19:33:29.111 30992 30992 E BarcodeAnalyser: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-06 19:33:29.111 30992 30992 E BarcodeAnalyser: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-06 19:33:29.111 30992 30992 E BarcodeAnalyser: 	at f5.g.run(Unknown Source:53)
03-06 19:33:29.111 30992 30992 E BarcodeAnalyser: 	at java.lang.Thread.run(Thread.java:920)
03-06 19:33:29.112 30992 30992 D BarcodeAnalyser: Image processed
```

The easiest workaround is to use the bundled version from GitHub release, but I expect the app to detect such errors and guide the user to do so.

**Comment by Fabi019** [comment]
Thanks for the feedback and your interest in the app.
Normally there should already be dialogs for notifying the user about the mlkit module. These should look like following:

<img width="200px" src="https://github.com/Fabi019/hid-barcode-scanner/assets/26741207/d6176fa9-4d7a-4dcc-9860-2c1a45013cb8"/><img width="200px" src="https://github.com/Fabi019/hid-barcode-scanner/assets/26741207/48ccd974-2c7e-4694-843e-22d42a250b90" />

However since this wasn't the case for you I will be looking into and see if I can improve this. If you still have the logcat available you could search for the tag "ModuleInstaller". There should be log outputs simmilar to the following:

> 11386-11386 ModuleInstaller         dev.fabik.bluetoothhid               D  Checking if module is present
> 11386-11386 ModuleInstaller         dev.fabik.bluetoothhid               D  Modules are not available
> 11386-11386 ModuleInstaller         dev.fabik.bluetoothhid               D  Modules installer started
> 11386-11386 ModuleInstaller         dev.fabik.bluetoothhid               D  Install state: 4
> 11386-11386 ModuleInstaller         dev.fabik.bluetoothhid               D  Modules installation completed

Or if the installation failed:

> 11386-11386 ModuleInstaller         dev.fabik.bluetoothhid               D  Checking if module is present
> 11386-11386 ModuleInstaller         dev.fabik.bluetoothhid               D  Modules are not available
> 11386-11386 ModuleInstaller         dev.fabik.bluetoothhid               D  Modules installer started
> 11386-11386 ModuleInstaller         dev.fabik.bluetoothhid               D  Install state: 5
> 11386-11386 ModuleInstaller         dev.fabik.bluetoothhid               D  Modules installation failed

**Comment by szescxz** [comment]
> Normally there should already be dialogs for notifying the user about the mlkit module. These should look like following:
> 
> <img alt="" width="200px" src="https://private-user-images.githubusercontent.com/26741207/310609542-d6176fa9-4d7a-4dcc-9860-2c1a45013cb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODYwMzgsIm5iZiI6MTcwOTc4NTczOCwicGF0aCI6Ii8yNjc0MTIwNy8zMTA2MDk1NDItZDYxNzZmYTktNGQ3YS00ZGNjLTk4NjAtMmMxYTQ1MDEzY2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0Mjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNTFkNGEzY2U4NzYyMzAzN2VhMTA0YTQ3ZDU0NWUwYjI2NjgwNWEwZjA0NzJjYjY1NTVkNWE1Mzg5NDk3MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Auvg62zMfW6oJ_G-VjRtB5X-R9kGoNJXnjbNarKzUw"><img alt="" width="200px" src="https://private-user-images.githubusercontent.com/26741207/310609547-48ccd974-2c7e-4694-843e-22d42a250b90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODYwMzgsIm5iZiI6MTcwOTc4NTczOCwicGF0aCI6Ii8yNjc0MTIwNy8zMTA2MDk1NDctNDhjY2Q5NzQtMmM3ZS00Njk0LTg0M2UtMjJkNDJhMjUwYjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0Mjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxOTg1Y2Y4MDk3ZDk4ZWVhMzM0MDRiYjQwZmYxOGExMjlhZmY1NjY5OWVhNTIxNTIzYWFkNDA4YWE2NmFhMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.buw4yyesHeuyHGLhsKBmcYmGnaJ6_EnUFrD1NgPY34g">
> 

I did see those after clearing Google Play Services data, but in some cases it just moved on after the "Please wait!" prompt, resulted in those logcat lines in the OP.

I'll do a full logcat again when I have time.
